### PR TITLE
Accept photos as files #14

### PR DESCRIPTION
**Pull request by kamo-develop**
The bot now accepts photos as files #14

### CODE REVIEW

**Comment by kamo-develop** [comment]
Sorry, there was a conflict in the code because I added the publish_post and enter_photo_as_document functions

**Comment by hexponent** [comment]
@kamo-develop If we need to add extra step after photo, we would have to make changes in both `enter_photo` and `enter_photo_as_document`, so I suggest moving common logic (file download + post) in separate `handle_photo` which accepts either `document` or `photo[-1]`

**Comment by kamo-develop** [comment]
@hexponent Ok, I'll do it. I will create a new PR later.

**Comment by mykolasolodukha** [comment]
@kamo-develop LGTM 👍

I would also propose adding a check for files so that e.g. `.pdf` files are not saved as `.jpg`s. However, it's optional at this stage.

Looking forward to more contributions from you!

**Pull request merged**
