### PR TITLE
Connect PostgreSQL

### PR DESCRIPTION
**Pull request by bodamat**
Connect to PostgreSQL on startup of the bot and disconnect the db when bot shutdown. Also at strartup add info about bot to the db

To test it, should add PostgreSQL connect url to `.env` file to key `DATABASE_URL`

### CODE REVIEW

**Review by Salz0 — CHANGES_REQUESTED** [review]

**Comment by Salz0** [comment]
Could you please resolve the conflicts or create a new PR?

**Comment by Salz0** [comment]
@mykolasolodukha could you take a look at this PR, can't run Docker for no apparent reason 🙏

**Review by Salz0 — APPROVED** [review]

**Comment by Salz0** [comment]
Thanks a lot bro!

**Comment by mykolasolodukha** [comment]
@bodamat at your revision, there's no `.DATABASE_URL` in `settings.settings` ([link](https://github.com/bodamat/telegram_flea/blob/connect-db/settings.py#L5-L13)), so the bot fails with 
> AttributeError: 'Settings' object has no attribute 'DATABASE_URL'

... and `.DATABASE_URL` is used in [`utils/tortoise_orm.py`](https://github.com/bodamat/telegram_flea/blob/connect-db/utils/tortoise_orm.py#L49)

Please be a bit more careful next time 🙂 

CC @Salz0

**Comment by Salz0** [comment]
> @bodamat at your revision, there's no `.DATABASE_URL` in `settings.settings` ([link](https://github.com/bodamat/telegram_flea/blob/connect-db/settings.py#L5-L13)), so the bot fails with 
> 
> > AttributeError: 'Settings' object has no attribute 'DATABASE_URL'
> 
> 
> 
> ... and `.DATABASE_URL` is used in [`utils/tortoise_orm.py`](https://github.com/bodamat/telegram_flea/blob/connect-db/utils/tortoise_orm.py#L49)
> 
> 
> 
> Please be a bit more careful next time 🙂 
> 
> 
> 
> CC @Salz0 

Preparing a big release with this fix

**Pull request merged**
